### ISSUE TITLE
Tool for custom fan control and power mode

### ISSUE THREAD

**Issue by johnfanv2** [novakcgx/linux-on-lenovo-legion#1]
I created a tool for custom fan curves, power modes, and other stuff for Lenovo Legion 5, Legion 7 etc. It is called LenovoLegionLinux and is on github [https://github.com/johnfanv2/LenovoLegionLinux](https://github.com/johnfanv2/LenovoLegionLinux). Maybe this is also useful for your list.

**Comment by cszach** [comment]
This looks really cool!! I will add it to my list.

**Comment by johnfanv2** [comment]
Great! Thanks a lot for including it!
