### ISSUE TITLE
Request for inclusion of battery optimization tips

### ISSUE THREAD

**Issue by akza07** [novakcgx/linux-on-lenovo-legion#14]
Device: LENOVO Legion Slim 5 16AHP9 83DH ( Ryzen 8845HS / 4060 )
Idle Drain of 23 Watt

I installed Fedora 40. Noticing battery drain. On a standard Nvidia driver installation and configuration with `envycontrol`, both iGPU and Hybrid mode has same 2hr 15min battery backup on idle.  The same configuration on Windows gives me about 6hr. So something is off here. So if you or anyone have any tips for it, Please update it in the document.

**Comment by kasra3422** [comment]
Do you have an external monitor connected? The HDMI and USB-C display ports are linked exclusively to the discrete GPU, which means the dGPU cannot be turned off when an external display is attached. Additionally, using the wrong driver may prevent the dGPU from entering low-power mode, even without an external monitor connected. Try using a tool like 'Mission Center' to check if the dGPU is active.

**Comment by akza07** [comment]
In integrated mode, the hardware is basically removed as far as linux knows so `nvidia-smi` doesn't work either. Thinking of installing the drivers directly. It could be rpm fusion drivers have some modifications I guess.

**Comment by akza07** [comment]
# An update on the battery issue.

Installing drivers both new Open Drivers and Proprietary drivers, They both are bad and never really turns off. They flip back n forth from 8 second of `ACTIVE` state then `SUSPENDED` for a fraction of second and `ACTIVE` again. The trigger seems to be some random Electron app or just coincidence. I get around 2hr of battery. Sometime GPU consumes 1W, 5W or 11W ( typical )

## Why not use something like `envycontrol` and force integrated GPU mode?
If you use it to force integrated mode, it will only use integrated GPU to render screen but the GPU will always consume 11W or P0 state. Ideally it should be suspended state.

## What's the solution?
Don't install Nvidia drivers but install `envycontrol` only and set it to integrated mode. You'll get 4hrs on normal use and 6hrs on low brightness and normal temps.

I'll update if and when I find a proper solution. `supergfxctl` is what many suggested but not seeing a device in mounted state doesn't mean it's off. That's only in Windows.
